# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastdev',
                'doc_host': 'https://simunaqv.github.io',
                'git_url': 'https://github.com/simunaqv/fastdev',
                'lib_path': 'fastdev'},
  'syms': {'fastdev.core': {'fastdev.core.foo': ('core.html#foo', 'fastdev/core.py')}}}
